spring:
  datasource:
    url: jdbc:mysql://localhost:3306/CNEvent?createDatabaseIfNotExist=true
    username: root
    password: Sushil@2003
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate.ddl-auto: update

server:
  port: 8081